var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-1,undefined);
subject.inc(1,undefined);
subject.inc(-1,"NotStrict");
subject.inc(1,"NotStrict_original_param");
subject.inc(1,undefined);
subject.inc(1,"Big_o");
subject.inc(1,"werw");
subject.weird(71,-1,41,"strict");
subject.weird(-71,1,-41,"strict");
subject.weird(71,-1,41,"NotStrict");
subject.weird(-71,1,-41,"NotStrict_original_param");
subject.weird(5041,1,1681,"strict");
subject.weird(5041,1,1681,"Big_o");
subject.weird(-71,1,-41,"werw");
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.normalize('');
subject.normalize("NotStrict");
subject.normalize("NotStrict_original_param");
subject.normalize('');
subject.normalize("Big_o");
subject.normalize("werw");
subject.format('','','');
subject.format('','','');
subject.format("NotStrict","NotStrict","NotStrict");
subject.format("NotStrict_original_param","NotStrict_original_param","NotStrict_original_param");
subject.format('','','');
subject.format("Big_o","Big_o","Big_o");
subject.format("werw","werw","werw");
subject.blackListNumber("(212) 555-5555");
subject.blackListNumber("(212) 555-5555");
subject.blackListNumber("NotStrict");
subject.blackListNumber("NotStrict_original_param");
subject.blackListNumber("(212) 555-5555");
subject.blackListNumber("Big_o");
subject.blackListNumber("werw");
